FROM ubuntu:20.04

WORKDIR /pysurfex

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y python3 python3-distutils curl libudunits2-dev libproj-dev libeccodes0 libeccodes-dev libnetcdf-dev netcdf-bin


# Install
COPY . .

ENV POETRY_HOME=/usr/local
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN poetry install
RUN poetry run pytest

